name: amar_wallet_assignment
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  fpdart: ^1.1.1
  dio: ^5.7.0
  bloc_concurrency: ^0.3.0
  device_info_plus: ^11.2.1
  android_id: ^0.4.0
  package_info_plus: ^8.1.3
  carousel_slider: ^5.0.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
